### ISSUE TITLE
systemctl service

### ISSUE THREAD

**Issue by mrkafk** [lxqt/lxqt-openssh-askpass#53]
Hello,

I found instructions given here don't work re path to SSH agent socket: https://github.com/lxqt/lxqt-openssh-askpass/blob/master/README.md

The reason for this is that if the service is started by `systemctl` as root, only root can read or write to the socket. I found this works:

```
[Unit]
Description=LXQT ssh agent

[Service]
Type=forking
ExecStart=/bin/su - myusername -c '/usr/bin/ssh-agent -a /run/user/1005/ssh-agent'

[Install]
WantedBy=default.target
```

**Comment by agaida** [comment]
and what should we do with this report - it says nothing, so i think closing it without any further processing is adaequate.
