### ISSUE TITLE
Use Wayland, not X11/XWayland

### ISSUE THREAD

**Issue by txtsd** [lxqt/lxqt-openssh-askpass#85]
##### Expected Behavior

Unlike `x11-ssh-askpass`, `lxqt-openssh-askpass` should display using wayland.

##### Current Behavior

Despite being a Qt application, it needs X11/XWayland to display.
![2022-10-24-13:49:33:43:754541215-424x128_grim](https://user-images.githubusercontent.com/768728/197482420-5262131a-215e-498c-a988-9fb30ae95075.png)
![2022-10-24-13:48:26:43:409000531-436x169_grim](https://user-images.githubusercontent.com/768728/197482352-483f665d-9e46-49a0-a1d7-855f93e10655.png)

##### Possible Solution

¯\\\_(ツ)\_/¯

##### Steps to Reproduce (for bugs)

1. Use a Wayland DE like Sway
2. Set `SSH_ASKPASS=lxqt-openssh-askpass` and restart `ssh-agent`
3. Trigger an askpass situation and notice that the dialog opens with XWayland
4. One could use `xeyes` to verify it

##### Context

I'm trying to use a pure Wayland environment, but there are some leftover programs that require XWayland to function.
##### System Information

* Distribution & Version: Archlinux
* Kernel: 6.0.2.zen1-1
* Qt Version: 5.15.6+kde+r180-2 / 6.4.0-2
* liblxqt Version: 1.1.0-3
* lxqt-build-tools Version: N/A
* Package version: 1.1.0-1

**Comment by X-dark** [comment]
You may have something misconfigured. It is not using XWayland on my side.

**Comment by txtsd** [comment]
I will test again today and let you know.

**Comment by adrelanos** [comment]
Any update?

**Comment by txtsd** [comment]
Woops. This completely slipped my mind. I'll let provide an update the next time I'm at my computer.

**Comment by Vladimir-csp** [comment]
I've checked on sway, lxqt-openssh-askpass does not use Xwayland, works natively.

Making it a dialog window from the application side would be nice though.

**Comment by txtsd** [comment]
```
λ lxqt-openssh-askpass -v
lxqt-openssh-askpass 1.4.0
liblxqt   1.4.0
Qt        5.15.11
```
I upgraded to this version from the core Arch repos, and it works well now.
