### ISSUE TITLE
In version 2.0.0 the input field is not focused automatically

### ISSUE THREAD

**Issue by romildo** [lxqt/lxqt-openssh-askpass#96]
With version 2.0.0, `lxqt-openssh-askpass` does not focus the input text field automatically anymore. This is the place where one types the password. The `OK` button is focused instead. Now one has to press TAB twice to reach the text input field in order to type the password.

![Screenshot from 2024-05-11 12-44-08](https://github.com/lxqt/lxqt-openssh-askpass/assets/1217934/0475e5bd-ed7b-4211-939b-66ecd1c711b5)

Tested in labwc-0.7.2 and in LXQt with Openbox.

##### Expected Behavior
When the lxqt-openssh-askpass application is launched and focused by the window manager, the text input field where one types the passwords should be focused.

##### Current Behavior
Instead, the `OK` button is focused.

##### Possible Solution
Maybe it is related to the migration to Qt6.

##### Steps to Reproduce (for bugs)
Launch `lxqt-openssh-askpass` from a terminal and see that the `OK` button is focused.

##### Context
I use the application for authentication for some applications, and I have to hit two more keystrokes (TAB) in order to reach the text input field prior to typing the password.

##### System Information
* Distribution & Version: NixOS unstable
* Kernel: Linux 6.8.9
* Qt Version: 6.7.0
* liblxqt Version: 2.0.0
* lxqt-build-tools Version: 2.0.0
* Package version: 2.0.0

**Comment by tsujan** [comment]
Thanks! Confirmed. The simple fix: https://github.com/lxqt/lxqt-openssh-askpass/pull/97
